name: Ejecutar CI Centralizado
# Comentario para hacer pull 3
on:
  push:
    branches: [ "master" ] # Se activa cuando subes algo a master

jobs:
  llamar-al-ci:
    # Aquí llamas a tu Repo 1 (CI-centralizado)
    uses: djbubble/ci-centralizado/.github/workflows/reusable-pipeline.yml@main
    secrets: 
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Pasamos directamente el secreto.
