name: PR Auto Tagger

# El robot se despierta cuando un Pull Request se cierra
on:
  pull_request:
    types: [closed]  # Sigue siendo este el evento aunque afinamos la lógica interna para que sea cuando el Squash & Merge.

jobs:
  tag-release:
    # Solo se ejecuta si el PR se cerró porque se aceptó (Merged)
    # y no si simplemente se canceló o cerró sin cambios.
    if: github.event.pull_request.merged == true
    # Genera una instancia de linux.
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # IMPORTANTE: Permiso para que el robot pueda crear el Tag

    steps:
      # Descargamos el código.
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }} # Nos aseguramos de estar en la rama destino (master).
          fetch-depth: 0 # Trae todo el historial para poder etiquetar correctamente

      - name: Extraer Version de la Plantilla
        id: get_version
        # Pasamos el cuerpo del PR como una variable segura.
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          # Extraemos el valor del campo 'Tag:' de la plantilla
          # Limpiamos saltos de línea (\r) y espacios (xargs)
          VERSION=$(echo "$PR_BODY" | grep "Tag:" | sed 's/.*Tag:[[:space:]]*//' | tr -d '\r' | xargs)
          
          if [ -z "$VERSION" ]; then
            echo "No se encontró tag en la plantilla. Saltando etiquetado."
            exit 0
          fi
          
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Versión detectada para la rama final: $VERSION"

      - name: Aplicar Tag al Código Mergeado
        if: steps.get_version.outputs.version != ''
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # Etiquetar el código ya mergeado (el resultado del squash)
          # El commit de Squash es el que está ahora mismo en la punta (HEAD) de master
          TAG_NAME="${{ steps.get_version.outputs.version }}"
          
          # Creamos el tag con un mensaje descriptivo que incluya el número de PR (tag anotado)
          git tag -a "$TAG_NAME" -m "Release $TAG_NAME de PR #${{ github.event.pull_request.number }}"
          
          # Subimos el tag
          git push origin "$TAG_NAME"
